version: '3.8'

services:
  backend:
    build: .
    container_name: java_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my_network
  db:
    image: mysql:
    container_name: phontathana.stoer.com_sql_db
    environment:
      MYSQL_ROOT_PASSWORD: root@phonrathana.-v.pass
      MYSQL_DATABASE: phonrathana.stoe.com.db
      MYSQL_USER: phontathana_user-v
      MYSQL_PASSWORD: secret1234
    ports:
      - "3000:3000"
    volumes:
      - ./mysql_data:/var/lib/mysql.db
    networks:
      - my_network

  webapp:
    image: nginx:latest
    container_name: phonrathana.stoer.com_web_app
    ports:
      - "8080:80"
    volumes:
      - ./webapp:/usr/share/nginx/html
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
