# === Firebase ===
FIREBASE_API_KEY=YOUR_FIREBASE_API_KEY
FIREBASE_AUTH_DOMAIN=YOUR_FIREBASE_AUTH_DOMAIN
FIREBASE_PROJECT_ID=YOUR_FIREBASE_PROJECT_ID

# === MongoDB Atlas ===
MONGO_URI=YOUR_MONGO_CONNECTION_URI

# === Stripe ===
STRIPE_SECRET_KEY=YOUR_STRIPE_SECRET_KEY

# === JWT Authentication ===
JWT_SECRET=YOUR_RANDOM_SECRET
